apiVersion: v1
kind: Pod
metadata:
  name: perlmutter-smoke
  namespace: airflow-demo
  annotations:
    nersc.sf/credentialSecretName: sfapi-client
    nersc.slurm/account: nstaff
    nersc.slurm/time: "00:05:00"
    nersc.slurm/mem: "1GB"
    nersc.slurm/qos: debug
    nersc.slurm/constraint: cpu
spec:
  automountServiceAccountToken: false
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: perlmutter-vk
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Equal
    value: nersc
    effect: NoSchedule
  containers:
  - name: smoke
    image: docker.io/library/alpine:3.20
    command: ["sh", "-lc"]
    args: ["echo hello from Perlmutter via vk-provider-nersc; date; hostname"]
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
