apiVersion: v1
kind: Secret
metadata:
  name: sfapi-client
type: Opaque
stringData:
  sf_api.json: |
    {
      "client_id": "<YOUR_SFAPI_CLIENT_ID>",
      "secret": {
        "kty": "RSA",
        "n": "<JWK_N>",
        "e": "<JWK_E>",
        "d": "<JWK_D>",
        "p": "<JWK_P>",
        "q": "<JWK_Q>",
        "dp": "<JWK_DP>",
        "dq": "<JWK_DQ>",
        "qi": "<JWK_QI>"
      }
    }
